spring:
  application:
    name: spring-boot-demo-dubbo-provider
server:
  port: 9090
dubbo:
  scan:
    base-packages: com.gusuchen.dubbo.consumer.service
  application:
    id: spring-boot-demo-dubbo-provider
    name: spring-boot-demo-dubbo-provider
    owner: gusuchen
  registry:
    id: zk-registry
    address: zookeeper://192.168.2.20:2181
  protocol:
    id: dubbo
    name: dubbo
    port: 20880
    serialization: kryo
